n = input('Write something: ')
print('The primitive type of this value is ', type(n))
print('Only has spaces: ', n.isspace())
print('Its a number: ', n.isnumeric())
print('It is alphabetical: ', n.isalpha())
print('It is alphanumeric: ', n.isalnum())
print('Is in capital letters: ', n.islower())
print('Is in lowecase: ', n.isupper())
print('Is capitalized: ', n.istitle())

